In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
data = pd.read_csv("DataSet/Train.csv")

c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGHGSN,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,RIMHI5ZGP,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,RIHOG1SZU,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,RIHOLMQWU,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,RIHO584ET,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [4]:
target = data.Col2

In [5]:
DataDimension = 2395

In [6]:
DataTenCol = data.iloc[:,1:DataDimension+1]

In [7]:
colunsToBeDropped = []
for i, item in enumerate(DataTenCol.dtypes):
    if item.type not in [np.int64,np.float64]:
        colunsToBeDropped.append("Col"+str(i+2))
#         print(i+2)
#         print(item.type)

In [8]:
colunsToBeDropped

['Col747', 'Col836']

In [9]:
# len(DataTenCol.Col836.isnull().values)

In [10]:
DataTenCol = DataTenCol.drop(colunsToBeDropped, axis=1)

In [11]:
DataTenCol.head()

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,9.114586e+03,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,2.013518e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,9.368338e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,4.304848e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,3.473444e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [12]:
DataTenCol.head()

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,9.114586e+03,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,2.013518e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,9.368338e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,4.304848e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,3.473444e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [13]:
DataTenCol.describe(include='all')

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
count,17521.000000,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,...,17521.000000,17521.000000,17521.000000,17521.000000,16347.000000,16347.000000,16335.000000,16347.00000,16347.000000,16335.000000
mean,0.100508,3.158967e+04,2.046540e+04,2.502937e+04,2.789385e+04,2.597734e+04,3.302600e+04,2.912693e+04,2.971069e+04,3.617392e+04,...,0.736202,0.595343,0.773757,0.639005,55.540038,55.015416,35.180961,17.99584,17.539977,10.359657
std,0.300685,7.612897e+05,7.136908e+05,6.018207e+05,6.091245e+05,7.211998e+05,7.488433e+05,2.175595e+05,2.981508e+05,2.612427e+05,...,0.910828,0.784953,0.921805,0.806286,53.269618,52.697069,34.956016,24.83891,24.685954,18.476447
min,0.000000,-8.555719e+07,-8.555719e+07,-7.011955e+07,-7.100920e+07,-8.480658e+07,-9.016250e+07,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,0.000000,2.742337e+03,2.007863e+03,1.857013e+03,2.562647e+03,2.973188e+03,3.822170e+03,1.824148e+03,1.787456e+03,3.505288e+03,...,0.000000,0.000000,0.000000,0.000000,21.000000,21.000000,12.000000,9.00000,9.000000,5.000000
50%,0.000000,9.308060e+03,6.642857e+03,6.236503e+03,8.464355e+03,1.036962e+04,1.303534e+04,5.705458e+03,5.536147e+03,8.832639e+03,...,0.000000,0.000000,0.000000,0.000000,42.000000,42.000000,27.000000,13.00000,13.000000,7.000000
75%,0.000000,3.053873e+04,2.156093e+04,2.068154e+04,2.773849e+04,2.645998e+04,3.359204e+04,1.852222e+04,1.753976e+04,2.341911e+04,...,1.000000,1.000000,1.000000,1.000000,74.000000,73.000000,47.000000,21.00000,21.000000,12.000000
max,1.000000,1.459355e+07,1.288980e+07,1.478068e+07,1.178075e+07,1.879882e+07,1.514035e+07,1.125630e+07,2.788633e+07,1.314762e+07,...,4.000000,4.000000,4.000000,4.000000,1305.000000,1305.000000,1211.000000,2205.00000,2205.000000,1831.000000

In [14]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(fill_value = 0, missing_values = np.NaN)

In [15]:
y = DataTenCol.iloc[:,0]

In [16]:
important_features = ['Col177',
 'Col877',
 'Col875',
 'Col18',
 'Col874',
 'Col636',
 'Col681',
 'Col586',
 'Col106',
 'Col915',
 'Col37',
 'Col933',
 'Col876',
 'Col26',
 'Col166',
 'Col614',
 'Col243',
 'Col163',
 'Col444',
 'Col179',
 'Col173',
 'Col872',
 'Col914',
 'Col519',
 'Col725',
 'Col21',
 'Col907',
 'Col175',
 'Col889',
 'Col13',
 'Col621',
 'Col603',
 'Col814',
 'Col246',
 'Col162',
 'Col579',
 'Col390',
 'Col912',
 'Col172',
 'Col257',
 'Col652',
 'Col633',
 'Col443',
 'Col24',
 'Col174',
 'Col25',
 'Col240',
 'Col167',
 'Col885',
 'Col9']

In [17]:
X = DataTenCol[important_features].copy()

In [18]:
input_dim = X.shape[1]

In [19]:
# X = DataTenCol.iloc[:,1:]

In [20]:
X.isnull().values.any()

True

In [21]:
X = pd.DataFrame(imp.fit_transform(X.values),index = X.index, columns = X.columns)

In [22]:
X.isnull().values.any()

False

In [23]:
# sns.pairplot(DataTenCol,hue='Col2')

In [24]:
X.head()

,Col177,Col877,Col875,Col18,Col874,Col636,Col681,Col586,Col106,Col915,...,Col652,Col633,Col443,Col24,Col174,Col25,Col240,Col167,Col885,Col9
0,0.983505,1.160181,4.015786,0.403366,4.015786,0.460104,-0.382431,0.333333,17.980863,1.048415,...,0.0000,0.000000,0.582386,1.297050,1.000000,0.137398,0.000000,0.341804,1.099273,1.285597e+04
1,0.893896,1.070587,2.984058,2.676398,2.984058,0.000000,0.454620,0.000000,0.957537,0.000000,...,0.0000,0.000000,1.836166,0.966620,0.371792,0.753892,0.000106,0.667423,1.288429,1.726538e+05
2,0.861632,0.258884,2.271018,2.203874,2.271018,0.002855,0.529382,1.666667,0.482401,1.000000,...,0.0020,0.000068,0.641678,0.735339,0.371792,0.808115,0.000089,0.223574,1.062294,5.320778e+06
3,0.976665,1.070587,3.065040,0.536304,3.065040,0.000000,0.567619,0.000000,0.223275,2.000000,...,0.0125,0.001353,0.973267,0.534531,0.371792,-0.125829,0.001089,0.114320,3.129732,3.577134e+05
4,0.988593,0.578306,3.598077,3.487721,3.598077,2.520248,0.476344,6.000000,-0.479454,0.000000,...,0.9049,0.010466,0.782257,1.563430,0.371792,-0.113101,0.009068,0.077244,4.826510,5.938358e+06

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [26]:
updatedX = sc.fit_transform(X)

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
XTrain,XTest,YTrain,YTest = train_test_split(updatedX,y,test_size=0.001)

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
import time
def base_model():
    model = Sequential()
    model.add(Dense(640, input_dim=input_dim, kernel_initializer='normal', activation='relu'))
    model.add(Dense(626, kernel_initializer='normal', activation='relu'))
    model.add(Dense(580, kernel_initializer='normal', activation='relu'))
    model.add(Dense(546, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(510, kernel_initializer='normal', activation='relu'))
    model.add(Dense(486, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(426, kernel_initializer='normal', activation='relu'))
    model.add(Dense(380, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(346, kernel_initializer='normal', activation='relu'))
    model.add(Dense(310, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(286, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(270, kernel_initializer='normal', activation='relu'))
    model.add(Dense(264, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(260, kernel_initializer='normal', activation='relu'))
    model.add(Dense(254, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(245, kernel_initializer='normal', activation='relu'))
    model.add(Dense(220, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(196, kernel_initializer='normal', activation='relu'))
    model.add(Dense(180, kernel_initializer='normal', activation='relu'))
    model.add(Dense(146, kernel_initializer='normal', activation='relu'))
    model.add(Dense(110, kernel_initializer='normal', activation='relu'))
    model.add(Dense(86, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(86, kernel_initializer='normal', activation='relu'))
    model.add(Dense(73, kernel_initializer='normal', activation='relu'))
    model.add(Dense(56, kernel_initializer='normal', activation='relu'))
    model.add(Dense(40, kernel_initializer='normal', activation='relu'))
    model.add(Dense(16, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal',activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
    return model

In [30]:
model1 = base_model()

WARNING: Logging before flag parsing goes to stderr.
W0928 17:58:57.602894  1796 deprecation.py:506] From c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0928 17:58:58.337928  1796 deprecation.py:323] From c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [ ]:
model1.fit(XTrain,YTrain, batch_size=40,epochs=150)

Epoch 1/150
17503/17503 [==============================] - 14s 796us/sample - loss: 0.3701 - acc: 0.8994
Epoch 2/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3358 - acc: 0.89940s - loss: 0.3373 -
Epoch 3/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3326 - acc: 0.89945s - los
Epoch 4/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3286 - acc: 0.8994
Epoch 5/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3273 - acc: 0.89940s - loss: 0.3273 - acc: 0.899
Epoch 6/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3278 - acc: 0.89940s - loss: 0.3279 - acc: 0.8
Epoch 7/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3273 - acc: 0.899410s - loss: 0.3228 - acc: - ETA: 9s - loss: 0.3240 - acc: 0 - ETA: 9s - loss: 0.3245 - acc: 0.9 -  - ETA: 2s - los
Epoch 8/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3273 - acc: 0.89941s - loss: 0.3272
Epoch 9/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3276 - acc: 0.89942s - loss
Epoch 10/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3275 - acc: 0.89941s - loss: 0.3289
Epoch 11/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3275 - acc: 0.89941s - loss:
Epoch 12/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3278 - acc: 0.8994
Epoch 13/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3271 - acc: 0.8994
Epoch 14/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3270 - acc: 0.89947s - loss: 0.3333 - acc: 0 - ETA - ETA: 3s - l - ETA: 1s - loss: 0.
Epoch 15/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3275 - acc: 0.8994
Epoch 16/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3269 - acc: 0.8994
Epoch 17/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3269 - acc: 0.89942s - loss: 0.3252 - - ETA: 1s - loss
Epoch 18/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3269 - acc: 0.8994
Epoch 19/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3274 - acc: 0.8994
Epoch 20/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3267 - acc: 0.89945s - loss: 0.32 - ETA: 0s - loss: 0.3264 - acc:
Epoch 21/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3268 - acc: 0.8994
Epoch 22/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3265 - acc: 0.8994
Epoch 23/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3268 - acc: 0.8994
Epoch 24/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3269 - acc: 0.8994
Epoch 25/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3270 - acc: 0.89940s - loss: 0.3269 - acc: 0.899
Epoch 26/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3271 - acc: 0.8994
Epoch 27/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3268 - acc: 0.89945s - loss: 0.3 - ETA: 3s - lo - ETA: 1s - loss: 0
Epoch 28/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3269 - acc: 0.8994
Epoch 29/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3265 - acc: 0.8994
Epoch 30/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3267 - acc: 0.8994
Epoch 31/150
17503/17503 [==============================] - ETA: 0s - loss: 0.3271 - acc: 0.8994- - 21s 1ms/sample - loss: 0.3271 - acc: 0.8994
Epoch 32/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3269 - acc: 0.8994
Epoch 33/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3266 - acc: 0.8994: 2
Epoch 34/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3269 - acc: 0.8994- ETA: 5s - loss: 0. - ETA: 4s - loss: 0.3279 - acc: 0.899 - ETA: 0s - loss: 0.3280 -
Epoch 35/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3268 - acc: 0.89949s -
Epoch 36/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3269 - acc: 0.89949s - loss: 0.3247 - acc: - ETA: 9s - loss:  - ETA: 7s - loss: 0.3270 - acc: 0.8
Epoch 37/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3267 - acc: 0.8994
Epoch 38/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3264 - acc: 0.8994
Epoch 39/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3267 - acc: 0.89942s - loss: - ETA: 0s - loss: 0.3263 -
Epoch 40/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3268 - acc: 0.89948s - loss: 0.3281 - acc:  - E - ETA: 5s - loss:  - E
Epoch 41/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3266 - acc: 0.89946s - loss: 0.3233 - ac - ETA: 5s - loss: 0.3214 - acc - ETA: 4s - loss: 0.3225 - acc: 0.90 - ET - ETA: 1s - loss: 0.32
Epoch 42/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3265 - acc: 0.899410 - ETA: - ETA: 2s - loss: 0.3234 - ETA: 0s - loss: 0.3248 -
Epoch 43/150
17503/17503 [==============================] - ETA: 0s - loss: 0.3267 - acc: 0.8994  ETA: 13s - loss: 0.3420 - acc: 0.89 - ETA: 13s - loss: 0.3407 - a - ETA: 13s - loss:  - ETA: 10s - loss: 0.3365 - acc: 0.89 - ETA: 10s - loss: 0.3369 - -  - ETA: 2 - 20s 1ms/sample - loss: 0.3266 - acc: 0.8994
Epoch 44/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3267 - acc: 0.8994TA: 8s - loss: 0 - ETA: 6s - loss: 0.3283 - acc: 0.8 - ETA: 2s - - ETA: 0s - loss: 0.3280 - acc:
Epoch 45/150
17503/17503 [==============================] - 16s 924us/sample - loss: 0.3269 - acc: 0.8994
Epoch 46/150
17503/17503 [==============================] - 10s 591us/sample - loss: 0.3265 - acc: 0.8994
Epoch 47/150
17503/17503 [==============================] - 10s 591us/sample - loss: 0.3266 - acc: 0.8994
Epoch 48/150
17503/17503 [==============================] - 10s 593us/sample - loss: 0.3267 - acc: 0.8994
Epoch 49/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3267 - acc: 0.8994 - loss:
Epoch 50/150
17503/17503 [==============================] - 10s 594us/sample - loss: 0.3264 - acc: 0.8994 - loss: 0.3264 -
Epoch 51/150
17503/17503 [==============================] - 10s 593us/sample - loss: 0.3267 - acc: 0.8994
Epoch 52/150
17503/17503 [==============================] - 10s 594us/sample - loss: 0.3266 - acc: 0.8994
Epoch 53/150
17503/17503 [==============================] - 10s 598us/sample - loss: 0.3267 - acc: 0.8994
Epoch 54/150
17503/17503 [==============================] - 10s 596us/sample - loss: 0.3267 - acc: 0.8994
Epoch 55/150
17503/17503 [==============================] - 11s 600us/sample - loss: 0.3268 - acc: 0.8994
Epoch 56/150
17503/17503 [==============================] - 13s 717us/sample - loss: 0.3266 - acc: 0.8994
Epoch 57/150
17503/17503 [==============================] - 16s 894us/sample - loss: 0.3267 - acc: 0.8994
Epoch 58/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3263 - acc: 0.8994
Epoch 59/150
17503/17503 [==============================] - 20s 1ms/sample - loss: 0.3267 - acc: 0.8994
Epoch 60/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3268 - acc: 0.8994
Epoch 61/150
17503/17503 [==============================] - 22s 1ms/sample - loss: 0.3267 - acc: 0.8994
Epoch 62/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3264 - acc: 0.8994
Epoch 63/150
17503/17503 [==============================] - 21s 1ms/sample - loss: 0.3266 - acc: 0.8994
Epoch 64/150
17503/17503 [==============================] - 19s 1ms/sample - loss: 0.3267 - acc: 0.8994
Epoch 65/150
17503/17503 [==============================] - 11s 633us/sample - loss: 0.3266 - acc: 0.8994
Epoch 66/150
17503/17503 [==============================] - 11s 616us/sample - loss: 0.3267 - acc: 0.8994
Epoch 67/150

17503/17503 [==============================] - 11s 612us/sample - loss: 0.3266 - acc: 0.8994
Epoch 68/150
17503/17503 [==============================] - 11s 619us/sample - loss: 0.3266 - acc: 0.8994
Epoch 69/150
17503/17503 [==============================] - 11s 632us/sample - loss: 0.3265 - acc: 0.8994
Epoch 70/150
17503/17503 [==============================] - 11s 641us/sample - loss: 0.3267 - acc: 0.8994
Epoch 71/150
17503/17503 [==============================] - 11s 655us/sample - loss: 0.3265 - acc: 0.8994
Epoch 72/150
17503/17503 [==============================] - 12s 677us/sample - loss: 0.3266 - acc: 0.8994
Epoch 73/150
17503/17503 [==============================] - 13s 728us/sample - loss: 0.3265 - acc: 0.8994
Epoch 74/150
17503/17503 [==============================] - 11s 626us/sample - loss: 0.3266 - acc: 0.8994
Epoch 75/150
17503/17503 [==============================] - 11s 617us/sample - loss: 0.3266 - acc: 0.8994
Epoch 76/150
17503/17503 [==============================] - 11s 627us/sample - loss: 0.3266 - acc: 0.8994
Epoch 77/150
17503/17503 [==============================] - 11s 608us/sample - loss: 0.3268 - acc: 0.8994 - loss: 0.3273 -
Epoch 78/150
17503/17503 [==============================] - 11s 611us/sample - loss: 0.3267 - acc: 0.8994
Epoch 79/150
17503/17503 [==============================] - 11s 628us/sample - loss: 0.3264 - acc: 0.8994
Epoch 80/150
17503/17503 [==============================] - 11s 620us/sample - loss: 0.3266 - acc: 0.8994
Epoch 81/150
17503/17503 [==============================] - 11s 633us/sample - loss: 0.3267 - acc: 0.8994 - loss: 0.3270 - ac
Epoch 82/150
17503/17503 [==============================] - 11s 614us/sample - loss: 0.3266 - acc: 0.8994
Epoch 83/150
17503/17503 [==============================] - 11s 602us/sample - loss: 0.3267 - acc: 0.8994
Epoch 84/150
 5360/17503 [========>.....................] - ETA: 7s - loss: 0.3221 - acc: 0.9015

In [ ]:
evaluation = model1.evaluate(XTrain,YTrain)

In [ ]:
evaluation = model1.evaluate(XTest,YTest)

In [ ]:
ypred = (model1.predict(XTest)>0.5)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(ypred,YTest)*100

In [ ]:
dataTest = pd.read_csv("DataSet/Test.csv")

In [ ]:
dataTest.head()

In [ ]:
# TestData = dataTest.iloc[:,1:DataDimension]

In [ ]:
TestData = dataTest[important_features].copy()

In [ ]:
TestData = TestData.drop(colunsToBeDropped, axis=1)

In [ ]:
TestData.head()

In [ ]:
TestData.isnull().values.any()

In [ ]:
np.all(X.columns == TestData.columns)

In [ ]:
convert_dict = {}
for i, item in enumerate(TestData.dtypes):
    if item.type not in [np.int64,np.float64]:
        convert_dict['Col'+str(i+3)] = np.float64
#         print(i+3)
#         print(item.type)

In [ ]:
TestData = TestData.replace('-',np.NaN).astype(convert_dict)

In [ ]:
TestData = pd.DataFrame(sc.transform(imp.transform(TestData.values)),index = TestData.index, columns = TestData.columns)

In [ ]:
TestData.isnull().values.any()

In [ ]:
TestData.head()

In [ ]:
out = [int(item[0]) for item in model1.predict(TestData)]

In [ ]:
outputDataFrameContents = {'Col1': dataTest.Col1.to_list(),'Col2':out}
outputDataFrame = pd.DataFrame(outputDataFrameContents)

In [ ]:
outputDataFrame.head()

In [ ]:
outfilename = "Output\Prediction{}.csv".format(int(time.time()))
outputDataFrame.to_csv(outfilename, index=False)