In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
data = pd.read_csv("DataSet/Train.csv")

c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGHGSN,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,RIMHI5ZGP,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,RIHOG1SZU,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,RIHOLMQWU,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,RIHO584ET,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [4]:
target = data.Col2

In [5]:
DataDimension = 2395

In [6]:
DataTenCol = data.iloc[:,1:DataDimension+1]

In [7]:
colunsToBeDropped = []
for i, item in enumerate(DataTenCol.dtypes):
    if item.type not in [np.int64,np.float64]:
        colunsToBeDropped.append("Col"+str(i+2))
#         print(i+2)
#         print(item.type)

In [8]:
colunsToBeDropped

['Col747', 'Col836']

In [9]:
# len(DataTenCol.Col836.isnull().values)

In [10]:
DataTenCol = DataTenCol.drop(colunsToBeDropped, axis=1)

In [11]:
DataTenCol.head()

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,9.114586e+03,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,2.013518e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,9.368338e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,4.304848e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,3.473444e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [12]:
input_dim = DataTenCol.shape[1]-1

In [13]:
DataTenCol.head()

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,9.114586e+03,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,2.013518e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,9.368338e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,4.304848e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,3.473444e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [14]:
DataTenCol.describe(include='all')

,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
count,17521.000000,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,1.752100e+04,...,17521.000000,17521.000000,17521.000000,17521.000000,16347.000000,16347.000000,16335.000000,16347.00000,16347.000000,16335.000000
mean,0.100508,3.158967e+04,2.046540e+04,2.502937e+04,2.789385e+04,2.597734e+04,3.302600e+04,2.912693e+04,2.971069e+04,3.617392e+04,...,0.736202,0.595343,0.773757,0.639005,55.540038,55.015416,35.180961,17.99584,17.539977,10.359657
std,0.300685,7.612897e+05,7.136908e+05,6.018207e+05,6.091245e+05,7.211998e+05,7.488433e+05,2.175595e+05,2.981508e+05,2.612427e+05,...,0.910828,0.784953,0.921805,0.806286,53.269618,52.697069,34.956016,24.83891,24.685954,18.476447
min,0.000000,-8.555719e+07,-8.555719e+07,-7.011955e+07,-7.100920e+07,-8.480658e+07,-9.016250e+07,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,0.000000,2.742337e+03,2.007863e+03,1.857013e+03,2.562647e+03,2.973188e+03,3.822170e+03,1.824148e+03,1.787456e+03,3.505288e+03,...,0.000000,0.000000,0.000000,0.000000,21.000000,21.000000,12.000000,9.00000,9.000000,5.000000
50%,0.000000,9.308060e+03,6.642857e+03,6.236503e+03,8.464355e+03,1.036962e+04,1.303534e+04,5.705458e+03,5.536147e+03,8.832639e+03,...,0.000000,0.000000,0.000000,0.000000,42.000000,42.000000,27.000000,13.00000,13.000000,7.000000
75%,0.000000,3.053873e+04,2.156093e+04,2.068154e+04,2.773849e+04,2.645998e+04,3.359204e+04,1.852222e+04,1.753976e+04,2.341911e+04,...,1.000000,1.000000,1.000000,1.000000,74.000000,73.000000,47.000000,21.00000,21.000000,12.000000
max,1.000000,1.459355e+07,1.288980e+07,1.478068e+07,1.178075e+07,1.879882e+07,1.514035e+07,1.125630e+07,2.788633e+07,1.314762e+07,...,4.000000,4.000000,4.000000,4.000000,1305.000000,1305.000000,1211.000000,2205.00000,2205.000000,1831.000000

In [15]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='mean', missing_values = np.NaN)

In [16]:
y = DataTenCol.iloc[:,0]

In [17]:
X = DataTenCol.iloc[:,1:]

In [18]:
X.isnull().values.any()

True

In [19]:
X = pd.DataFrame(imp.fit_transform(X.values),index = X.index, columns = X.columns)

In [20]:
X.isnull().values.any()

False

In [21]:
# sns.pairplot(DataTenCol,hue='Col2')

In [22]:
X.head()

,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,9.114586e+03,3.043078e+04,...,0.0,1.0,0.0,1.0,214.0,214.0,68.0,22.0,22.0,7.0
1,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,2.013518e+05,1.859404e+05,...,0.0,0.0,0.0,0.0,41.0,41.0,38.0,12.0,12.0,11.0
2,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,9.368338e+06,1.113330e+07,...,0.0,1.0,1.0,0.0,378.0,378.0,310.0,21.0,21.0,16.0
3,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,4.304848e+05,4.065539e+05,...,0.0,0.0,0.0,0.0,702.0,702.0,644.0,951.0,951.0,743.0
4,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,3.473444e+06,3.262168e+06,...,0.0,0.0,0.0,0.0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [24]:
updatedX = sc.fit_transform(X)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
XTrain,XTest,YTrain,YTest = train_test_split(updatedX,y,test_size=0.001)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
import time
def base_model():
    model = Sequential()
    model.add(Dense(640, input_dim=input_dim, kernel_initializer='normal', activation='relu'))
    model.add(Dense(626, kernel_initializer='normal', activation='relu'))
    model.add(Dense(580, kernel_initializer='normal', activation='relu'))
    model.add(Dense(546, kernel_initializer='normal', activation='relu'))
    model.add(Dense(510, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(486, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(426, kernel_initializer='normal', activation='relu'))
    model.add(Dense(380, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(346, kernel_initializer='normal', activation='relu'))
    model.add(Dense(310, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(286, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(270, kernel_initializer='normal', activation='relu'))
    model.add(Dense(264, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(260, kernel_initializer='normal', activation='relu'))
    model.add(Dense(254, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(245, kernel_initializer='normal', activation='relu'))
    model.add(Dense(220, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(196, kernel_initializer='normal', activation='relu'))
    model.add(Dense(180, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(146, kernel_initializer='normal', activation='relu'))
    model.add(Dense(110, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(86, kernel_initializer='normal', activation='relu'))
    model.add(Flatten())
    model.add(Dropout(0.2))
    model.add(Dense(86, kernel_initializer='normal', activation='relu'))
    model.add(Dense(73, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(56, kernel_initializer='normal', activation='relu'))
    model.add(Dense(40, kernel_initializer='normal', activation='tanh'))
    model.add(Dense(16, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal',activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
    return model

In [28]:
model1 = base_model()

WARNING: Logging before flag parsing goes to stderr.
W0930 22:25:22.114565 12056 deprecation.py:506] From c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\keras\initializers.py:143: calling RandomNormal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0930 22:25:23.302023 12056 deprecation.py:323] From c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [29]:
model1.fit(XTrain,YTrain, batch_size=40,epochs=150)

Epoch 1/150
17503/17503 [==============================] - 14s 818us/sample - loss: 0.3479 - acc: 0.8992 - los
Epoch 2/150
17503/17503 [==============================] - 11s 653us/sample - loss: 0.3267 - acc: 0.8994
Epoch 3/150
17503/17503 [==============================] - 11s 609us/sample - loss: 0.3270 - acc: 0.8994
Epoch 4/150
17503/17503 [==============================] - 10s 591us/sample - loss: 0.3272 - acc: 0.8994
Epoch 5/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3275 - acc: 0.8994
Epoch 6/150
17503/17503 [==============================] - 10s 595us/sample - loss: 0.3273 - acc: 0.8994
Epoch 7/150
17503/17503 [==============================] - 10s 592us/sample - loss: 0.3272 - acc: 0.8994
Epoch 8/150
17503/17503 [==============================] - 10s 596us/sample - loss: 0.3271 - acc: 0.8994
Epoch 9/150
17503/17503 [==============================] - 10s 593us/sample - loss: 0.3268 - acc: 0.8994
Epoch 10/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3271 - acc: 0.8994
Epoch 11/150
17503/17503 [==============================] - 10s 592us/sample - loss: 0.3271 - acc: 0.8994
Epoch 12/150
17503/17503 [==============================] - 10s 594us/sample - loss: 0.3268 - acc: 0.8994
Epoch 13/150
17503/17503 [==============================] - 10s 596us/sample - loss: 0.3273 - acc: 0.8994
Epoch 14/150
17503/17503 [==============================] - 10s 598us/sample - loss: 0.3271 - acc: 0.8994
Epoch 15/150
17503/17503 [==============================] - 10s 593us/sample - loss: 0.3271 - acc: 0.8994
Epoch 16/150
17503/17503 [==============================] - 10s 595us/sample - loss: 0.3268 - acc: 0.8994
Epoch 17/150
17503/17503 [==============================] - 10s 574us/sample - loss: 0.3275 - acc: 0.8994
Epoch 18/150
17503/17503 [==============================] - 10s 578us/sample - loss: 0.3270 - acc: 0.8994
Epoch 19/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3268 - acc: 0.8994
Epoch 20/150
17503/17503 [==============================] - 10s 587us/sample - loss: 0.3271 - acc: 0.8994
Epoch 21/150
17503/17503 [==============================] - 10s 578us/sample - loss: 0.3271 - acc: 0.8994
Epoch 22/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3271 - acc: 0.8994
Epoch 23/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3268 - acc: 0.8994
Epoch 24/150
17503/17503 [==============================] - 10s 585us/sample - loss: 0.3271 - acc: 0.8994
Epoch 25/150
17503/17503 [==============================] - 10s 588us/sample - loss: 0.3268 - acc: 0.8994
Epoch 26/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3270 - acc: 0.8994
Epoch 27/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3271 - acc: 0.8994
Epoch 28/150
17503/17503 [==============================] - 11s 600us/sample - loss: 0.3268 - acc: 0.8994
Epoch 29/150
17503/17503 [==============================] - 12s 693us/sample - loss: 0.3269 - acc: 0.8994
Epoch 30/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3270 - acc: 0.8994
Epoch 31/150
17503/17503 [==============================] - 10s 599us/sample - loss: 0.3268 - acc: 0.8994
Epoch 32/150
17503/17503 [==============================] - 11s 654us/sample - loss: 0.3267 - acc: 0.8994
Epoch 33/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3270 - acc: 0.8994
Epoch 34/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3268 - acc: 0.8994
Epoch 35/150
17503/17503 [==============================] - 10s 578us/sample - loss: 0.3269 - acc: 0.8994
Epoch 36/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3271 - acc: 0.8994
Epoch 37/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 38/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3268 - acc: 0.8994
Epoch 39/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3273 - acc: 0.8994
Epoch 40/150
17503/17503 [==============================] - 10s 588us/sample - loss: 0.3268 - acc: 0.8994
Epoch 41/150
17503/17503 [==============================] - 10s 573us/sample - loss: 0.3268 - acc: 0.8994
Epoch 42/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3269 - acc: 0.8994
Epoch 43/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3268 - acc: 0.8994
Epoch 44/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3270 - acc: 0.8994
Epoch 45/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3268 - acc: 0.8994
Epoch 46/150
17503/17503 [==============================] - 10s 573us/sample - loss: 0.3268 - acc: 0.8994
Epoch 47/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3268 - acc: 0.8994
Epoch 48/150
17503/17503 [==============================] - 10s 571us/sample - loss: 0.3268 - acc: 0.8994
Epoch 49/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3270 - acc: 0.8994
Epoch 50/150
17503/17503 [==============================] - 10s 574us/sample - loss: 0.3270 - acc: 0.8994
Epoch 51/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3270 - acc: 0.8994
Epoch 52/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3267 - acc: 0.8994
Epoch 53/150
17503/17503 [==============================] - 10s 571us/sample - loss: 0.3270 - acc: 0.8994
Epoch 54/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 55/150
17503/17503 [==============================] - 10s 573us/sample - loss: 0.3269 - acc: 0.8994
Epoch 56/150
17503/17503 [==============================] - 10s 580us/sample - loss: 0.3269 - acc: 0.8994
Epoch 57/150
17503/17503 [==============================] - 11s 628us/sample - loss: 0.3269 - acc: 0.8994
Epoch 58/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3270 - acc: 0.8994
Epoch 59/150
17503/17503 [==============================] - 10s 571us/sample - loss: 0.3268 - acc: 0.8994
Epoch 60/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3269 - acc: 0.8994
Epoch 61/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3270 - acc: 0.8994
Epoch 62/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 63/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3266 - acc: 0.8994
Epoch 64/150
17503/17503 [==============================] - 11s 652us/sample - loss: 0.3269 - acc: 0.8994
Epoch 65/150
17503/17503 [==============================] - 10s 600us/sample - loss: 0.3268 - acc: 0.8994
Epoch 66/150
17503/17503 [==============================] - 10s 572us/sample - loss: 0.3267 - acc: 0.8994
Epoch 67/150
17503/17503 [==============================] - 10s 574us/sample - loss: 0.3268 - acc: 0.8994
Epoch 68/150
17503/17503 [==============================] - 10s 578us/sample - loss: 0.3267 - acc: 0.8994
Epoch 69/150
17503/17503 [==============================] - 10s 572us/sample - loss: 0.3267 - acc: 0.8994
Epoch 70/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3269 - acc: 0.8994
Epoch 71/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3266 - acc: 0.8994
Epoch 72/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3269 - acc: 0.8994
Epoch 73/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3267 - acc: 0.8994
Epoch 74/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3268 - acc: 0.8994
Epoch 75/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3268 - acc: 0.8994
Epoch 76/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3266 - acc: 0.8994
Epoch 77/150
17503/17503 [==============================] - 10s 588us/sample - loss: 0.3267 - acc: 0.8994
Epoch 78/150

17503/17503 [==============================] - 11s 612us/sample - loss: 0.3267 - acc: 0.8994
Epoch 79/150
17503/17503 [==============================] - 10s 598us/sample - loss: 0.3267 - acc: 0.8994
Epoch 80/150
17503/17503 [==============================] - 10s 593us/sample - loss: 0.3269 - acc: 0.8994
Epoch 81/150
17503/17503 [==============================] - 10s 592us/sample - loss: 0.3268 - acc: 0.8994 - loss: 0.3278 - acc:
Epoch 82/150
17503/17503 [==============================] - 10s 592us/sample - loss: 0.3268 - acc: 0.8994
Epoch 83/150
17503/17503 [==============================] - 10s 585us/sample - loss: 0.3269 - acc: 0.8994
Epoch 84/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3268 - acc: 0.8994
Epoch 85/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3268 - acc: 0.8994
Epoch 86/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3267 - acc: 0.8994
Epoch 87/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3268 - acc: 0.8994
Epoch 88/150
17503/17503 [==============================] - 10s 586us/sample - loss: 0.3268 - acc: 0.8994
Epoch 89/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3269 - acc: 0.8994
Epoch 90/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3267 - acc: 0.8994
Epoch 91/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3268 - acc: 0.8994
Epoch 92/150
17503/17503 [==============================] - 10s 586us/sample - loss: 0.3267 - acc: 0.8994
Epoch 93/150
17503/17503 [==============================] - 10s 598us/sample - loss: 0.3267 - acc: 0.8994
Epoch 94/150
17503/17503 [==============================] - 10s 583us/sample - loss: 0.3268 - acc: 0.8994
Epoch 95/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3266 - acc: 0.8994
Epoch 96/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3267 - acc: 0.8994
Epoch 97/150
17503/17503 [==============================] - 10s 583us/sample - loss: 0.3268 - acc: 0.8994
Epoch 98/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3268 - acc: 0.8994
Epoch 99/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 100/150
17503/17503 [==============================] - 10s 587us/sample - loss: 0.3269 - acc: 0.8994
Epoch 101/150
17503/17503 [==============================] - 10s 588us/sample - loss: 0.3268 - acc: 0.8994
Epoch 102/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3268 - acc: 0.8994
Epoch 103/150
17503/17503 [==============================] - 10s 585us/sample - loss: 0.3267 - acc: 0.8994
Epoch 104/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3267 - acc: 0.8994
Epoch 105/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3267 - acc: 0.8994
Epoch 106/150
17503/17503 [==============================] - 10s 581us/sample - loss: 0.3267 - acc: 0.8994
Epoch 107/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3267 - acc: 0.8994
Epoch 108/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 109/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3267 - acc: 0.8994
Epoch 110/150
17503/17503 [==============================] - 10s 588us/sample - loss: 0.3267 - acc: 0.8994
Epoch 111/150
17503/17503 [==============================] - 11s 604us/sample - loss: 0.3268 - acc: 0.8994
Epoch 112/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3266 - acc: 0.8994
Epoch 113/150
17503/17503 [==============================] - 10s 583us/sample - loss: 0.3268 - acc: 0.8994
Epoch 114/150
17503/17503 [==============================] - 10s 583us/sample - loss: 0.3268 - acc: 0.8994
Epoch 115/150
17503/17503 [==============================] - 10s 591us/sample - loss: 0.3268 - acc: 0.8994
Epoch 116/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3267 - acc: 0.8994
Epoch 117/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3267 - acc: 0.8994
Epoch 118/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3266 - acc: 0.8994
Epoch 119/150
17503/17503 [==============================] - 10s 589us/sample - loss: 0.3267 - acc: 0.8994
Epoch 120/150
17503/17503 [==============================] - 10s 580us/sample - loss: 0.3267 - acc: 0.8994
Epoch 121/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3266 - acc: 0.8994
Epoch 122/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3267 - acc: 0.8994
Epoch 123/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3266 - acc: 0.8994
Epoch 124/150
17503/17503 [==============================] - 10s 580us/sample - loss: 0.3267 - acc: 0.8994
Epoch 125/150
17503/17503 [==============================] - 10s 580us/sample - loss: 0.3266 - acc: 0.8994
Epoch 126/150
17503/17503 [==============================] - 10s 584us/sample - loss: 0.3267 - acc: 0.8994
Epoch 127/150
17503/17503 [==============================] - 10s 576us/sample - loss: 0.3267 - acc: 0.8994
Epoch 128/150
17503/17503 [==============================] - 10s 573us/sample - loss: 0.3267 - acc: 0.8994
Epoch 129/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3267 - acc: 0.8994
Epoch 130/150
17503/17503 [==============================] - 10s 579us/sample - loss: 0.3268 - acc: 0.8994
Epoch 131/150
17503/17503 [==============================] - 11s 611us/sample - loss: 0.3267 - acc: 0.8994
Epoch 132/150
17503/17503 [==============================] - 10s 574us/sample - loss: 0.3267 - acc: 0.8994
Epoch 133/150
17503/17503 [==============================] - 10s 571us/sample - loss: 0.3268 - acc: 0.8994
Epoch 134/150
17503/17503 [==============================] - 10s 573us/sample - loss: 0.3267 - acc: 0.8994
Epoch 135/150
17503/17503 [==============================] - 10s 572us/sample - loss: 0.3268 - acc: 0.8994
Epoch 136/150
17503/17503 [==============================] - 11s 609us/sample - loss: 0.3266 - acc: 0.8994 - loss: 0.3265 -
Epoch 137/150
17503/17503 [==============================] - 10s 577us/sample - loss: 0.3266 - acc: 0.8994
Epoch 138/150
17503/17503 [==============================] - 10s 591us/sample - loss: 0.3267 - acc: 0.8994
Epoch 139/150
17503/17503 [==============================] - 11s 602us/sample - loss: 0.3266 - acc: 0.8994
Epoch 140/150
17503/17503 [==============================] - 10s 590us/sample - loss: 0.3266 - acc: 0.8994
Epoch 141/150
17503/17503 [==============================] - 11s 601us/sample - loss: 0.3267 - acc: 0.8994
Epoch 142/150
17503/17503 [==============================] - 11s 606us/sample - loss: 0.3267 - acc: 0.8994
Epoch 143/150
17503/17503 [==============================] - 10s 600us/sample - loss: 0.3267 - acc: 0.8994
Epoch 144/150
17503/17503 [==============================] - 10s 582us/sample - loss: 0.3268 - acc: 0.8994
Epoch 145/150
17503/17503 [==============================] - 11s 609us/sample - loss: 0.3265 - acc: 0.8994
Epoch 146/150
17503/17503 [==============================] - 11s 638us/sample - loss: 0.3265 - acc: 0.8994
Epoch 147/150
17503/17503 [==============================] - 11s 611us/sample - loss: 0.3266 - acc: 0.8994
Epoch 148/150
17503/17503 [==============================] - 10s 580us/sample - loss: 0.3266 - acc: 0.8994
Epoch 149/150
17503/17503 [==============================] - 10s 575us/sample - loss: 0.3268 - acc: 0.8994
Epoch 150/150
17503/17503 [==============================] - 10s 572us/sample - loss: 0.3268 - acc: 0.8994

In [30]:
evaluation = model1.evaluate(XTrain,YTrain)

17503/17503 [==============================] - 4s 220us/sample - loss: 0.3264 - acc: 0.8994

In [31]:
evaluation = model1.evaluate(XTest,YTest)

18/18 [==============================] - 0s 681us/sample - loss: 0.1053 - acc: 1.0000

In [55]:
ypred = (model1.predict(XTest)>0.5)

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
accuracy_score(ypred,YTest)*100

100.0

In [35]:
dataTest = pd.read_csv("DataSet/Test.csv")

c:\users\chira\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [36]:
dataTest.head()

,Col1,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGD58ZWD,8.167140e+04,8.614542e+04,7.532296e+04,7.532296e+04,1.125174e+05,1.002778e+05,2.038915e+04,3.053853e+04,8.395911e+04,...,0,0,0,0,44.0,44.0,23.0,41.0,41.0,36.0
1,RIH660YDS,-1.362824e+07,-4.493043e+06,-3.777257e+06,-4.493043e+06,-4.749764e+06,-4.749764e+06,1.147556e+07,1.147556e+07,1.272055e+07,...,1,1,2,2,1234.0,1234.0,680.0,154.0,153.0,86.0
2,RIH660Q96,1.302700e+06,1.341449e+06,1.240085e+06,1.341449e+06,1.477503e+06,1.477503e+06,3.904086e+05,3.904086e+05,4.979106e+05,...,0,0,0,0,33.0,24.0,19.0,3.0,1.0,1.0
3,RIYDO15W1,1.932258e+05,1.454433e+05,1.929148e+05,1.454433e+05,1.318250e+04,1.318250e+04,8.650108e+04,8.650108e+04,5.896693e+03,...,0,0,0,0,8.0,8.0,3.0,7.0,7.0,3.0
4,RIYBGC1ZD,3.913385e+05,1.987337e+05,1.703432e+05,1.987337e+05,3.046536e+05,3.046536e+05,2.528307e+05,2.528307e+05,3.034449e+05,...,0,0,0,0,7.0,7.0,7.0,6.0,6.0,5.0

In [37]:
TestData = dataTest.iloc[:,1:DataDimension]

In [38]:
TestData = TestData.drop(colunsToBeDropped, axis=1)

In [39]:
TestData.head()

,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,8.167140e+04,8.614542e+04,7.532296e+04,7.532296e+04,1.125174e+05,1.002778e+05,2.038915e+04,3.053853e+04,8.395911e+04,8.138800e+04,...,0,0,0,0,44.0,44.0,23.0,41.0,41.0,36.0
1,-1.362824e+07,-4.493043e+06,-3.777257e+06,-4.493043e+06,-4.749764e+06,-4.749764e+06,1.147556e+07,1.147556e+07,1.272055e+07,1.272055e+07,...,1,1,2,2,1234.0,1234.0,680.0,154.0,153.0,86.0
2,1.302700e+06,1.341449e+06,1.240085e+06,1.341449e+06,1.477503e+06,1.477503e+06,3.904086e+05,3.904086e+05,4.979106e+05,4.979106e+05,...,0,0,0,0,33.0,24.0,19.0,3.0,1.0,1.0
3,1.932258e+05,1.454433e+05,1.929148e+05,1.454433e+05,1.318250e+04,1.318250e+04,8.650108e+04,8.650108e+04,5.896693e+03,5.896693e+03,...,0,0,0,0,8.0,8.0,3.0,7.0,7.0,3.0
4,3.913385e+05,1.987337e+05,1.703432e+05,1.987337e+05,3.046536e+05,3.046536e+05,2.528307e+05,2.528307e+05,3.034449e+05,3.034449e+05,...,0,0,0,0,7.0,7.0,7.0,6.0,6.0,5.0

In [40]:
TestData.isnull().values.any()

True

In [41]:
np.all(X.columns == TestData.columns)

True

In [42]:
convert_dict = {}
for i, item in enumerate(TestData.dtypes):
    if item.type not in [np.int64,np.float64]:
        convert_dict['Col'+str(i+3)] = np.float64
#         print(i+3)
#         print(item.type)

In [43]:
TestData = TestData.replace('-',np.NaN).astype(convert_dict)

In [44]:
TestData = pd.DataFrame(sc.transform(imp.transform(TestData.values)),index = TestData.index, columns = TestData.columns)

In [45]:
TestData.isnull().values.any()

False

In [46]:
TestData.head()

,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,Col11,Col12,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,0.065787,0.092031,0.083571,0.077867,0.119998,0.089810,-0.040164,0.002777,0.182920,0.169411,...,-0.808301,-0.758465,-0.839418,-0.792551,-0.224286,-0.216415,-0.360905,0.958843,0.983903,1.437271
1,-17.943529,-6.324359,-6.318152,-7.422236,-6.622128,-6.387087,52.614364,38.390546,48.555392,46.863933,...,0.289632,0.515532,1.330301,1.688029,22.903874,23.163030,19.105090,5.668829,5.681133,4.240023
2,1.669728,1.850971,2.019024,2.156526,2.012712,1.929000,1.660658,1.209818,1.767513,1.708226,...,-0.808301,-0.758465,-0.839418,-0.792551,-0.438075,-0.609347,-0.479419,-0.625046,-0.693679,-0.524656
3,0.212325,0.175120,0.278970,0.192986,-0.017742,-0.026500,0.263725,0.190481,-0.115900,-0.109486,...,-0.808301,-0.758465,-0.839418,-0.792551,-0.923961,-0.923693,-0.953477,-0.458321,-0.442042,-0.412546
4,0.472565,0.249791,0.241464,0.280476,0.386418,0.362740,1.028271,0.748368,1.023105,0.989785,...,-0.808301,-0.758465,-0.839418,-0.792551,-0.943396,-0.943339,-0.834963,-0.500002,-0.483981,-0.300436

In [47]:
out = [int(item[0]) for item in model1.predict(TestData)]

In [48]:
outputDataFrameContents = {'Col1': dataTest.Col1.to_list(),'Col2':out}
outputDataFrame = pd.DataFrame(outputDataFrameContents)

In [49]:
outputDataFrame.head()

        Col1  Col2
0  RIGD58ZWD     0
1  RIH660YDS     0
2  RIH660Q96     0
3  RIYDO15W1     0
4  RIYBGC1ZD     0

In [50]:
outfilename = "Output\Prediction{}.csv".format(int(time.time()))
outputDataFrame.to_csv(outfilename, index=False)